apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-ingressroute-certificate
spec:
  secretName: jellyfin-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - jellyfin.eggenberg.io