apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingressroute
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`jellyfin.eggenberg.io`)
    kind: Rule
    services:
    - name: jellyfin
      port: 8096
  tls:
    secretName: jellyfin-certificate-secret