# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http: 
  use_x_forwarded_for: true 
  trusted_proxies: 
  - 10.10.20.0/24

lovelace:
  mode: yaml
  resources: !include lovelace_resources.yaml
  dashboards:
    home-dashboard:
      mode: yaml
      title: Home
      show_in_sidebar: true
      icon: mdi:home
      filename: dashboards/home.yaml
    lights-dashboard:
      mode: yaml
      title: Lights
      show_in_sidebar: true
      icon: mdi:lightbulb-group
      filename: dashboards/lights.yaml
    media-dashboard:
      mode: yaml
      title: Media
      show_in_sidebar: true
      icon: mdi:speaker-multiple
      filename: dashboards/media.yaml
    rooms-dashboard:
      mode: yaml
      title: Rooms
      show_in_sidebar: true
      icon: mdi:floor-plan
      filename: dashboards/rooms.yaml
    cleaning-dashboard:
      mode: yaml
      title: Cleaning
      show_in_sidebar: true
      icon: mdi:robot-vacuum
      filename: dashboards/cleaning.yaml