apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingressroute
  namespace: minio-system
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`api.minio.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: minio
      port: 9000
  - match: Host(`ui.minio.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: minio-console
      port: 9001
  tls:
    secretName: minio-certificate-secret