apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-ingressroute-certificate
  namespace: gitlab
spec:
  secretName: gitlab-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - git.eggenberg.io
  - registry.git.eggenberg.io