apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-ingressroute
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`git.eggenberg.io`)
    kind: Rule
    services:
    - name: gitlab-webservice-default
      port: 8181
  - match: Host(`registry.git.eggenberg.io`)
    kind: Rule
    services:
    - name: gitlab-registry
      port: 5000
  tls:
    secretName: gitlab-certificate-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab-ssh-ingressroute
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
  - ssh
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name: gitlab-gitlab-shell
      port: 2222