---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-storage-secret
  namespace: gitlab
spec:
  encryptedData:
    config: AgBHzsELhnzdk9ssqGgce0EuFwadtxJVrz8jZuidE8GdxktOmGxIWxXdx2GWmpYF81oDYBtXcUm41yAyFRdGS0mQWZL5QBR1YuF8WpDzuumpmi58lpkZ9EHpF5yU3TPremJM/Ch8PRhe/Pot6YcNbcg2hwZLto1I4nE5BjjXUcUcVkgOhhcB6JtmR9GHwHSR9xrkb7ULUk4eZ1N8AldttaLu9E9W5Vo/hw8SfYdDaCNNVmGw1yDs3K3fn6bk+ZI+B5sYomXvOFYNOodorQrTQYUnpE2/GYZgrUW9uhP4JMC/jGSqTyUU6iBdXNtQK6NOt5HXIlOqDLLUophoRxDfKFwAJISw9gdX26cHSW3EGSnkuY3HlC7pSTAVAvE+RUsV3wMO4/lVZIjNWvqJuaLeZeE/0snsRs6nwRNYiN5vrxKA5QW8QAGkfzJEG6KwfD0FpASOIa0Vabr8w92cA4D0zaAJztinds8/1Zibw2x8Jbgfw9PyqmoEZj0o4zr33iAFTngTxtZnruPMATpZOmYGIRzaSXgbpVbwrD8gtJqc1HKNbtVIF/yb8HTmCyulziuHC7VJRefNlAFkpMpxkxEs5vJ8g7jidwtEnTPkRUrfUpsUHUU/ybg6RP4c/zBRUL+KxarmutST/Js8lKjsYMkm3v9jZdLCchzLTVGRZ3PB2QOjrpPj2zXX8cFaQGsUBetdpsf/EL+OL5FuWzb6ZQw5wYqLdPwC+qd9oXNXZvpgijNcj60CTsMFFPN1HqmU9L9KGZCnl7UBtCXY6U45hMwyMnYHvzTQS4GsPfehhzem33AWssU7Q8Ahpavs6lne1Tm6KUCfF+q8in0DIjI2KQgU7pDhZBfOIkTOD/OIw6JI6gZauK1zmH+RAcW5Ncp2qMVNllTp+2G7y/FANa0qJlDSmrK7xQTioZB4WTIQ/QCZg6BRfNBbV9d70PPqEtVUaTzsWzWSK8vfg7fJmrtdIxcE1lCv
  template:
    metadata:
      creationTimestamp: null
      name: registry-storage-secret
      namespace: gitlab
    type: Opaque
