apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr-ingressroute
  namespace: media
spec:
  ingressClassName: traefik-internal
  entryPoints:
  - websecure
  routes:
  - match: Host(`huntarr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: huntarr
      port: 9705
  tls:
    secretName: huntarr-certificate-secret