apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cleanuparr-ingressroute
  namespace: media
spec:
  ingressClassName: traefik-internal
  entryPoints:
  - websecure
  routes:
  - match: Host(`cleanuparr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: cleanuparr
      port: 11011
  tls:
    secretName: cleanuparr-certificate-secret