apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-ingressroute-certificate
spec:
  secretName: immich-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - immich.eggenberg.io
