apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingressroute
spec:
  ingressClassName: traefik-public
  entryPoints:
  - websecure
  routes:
  - match: Host(`immich.eggenberg.io`)
    kind: Rule
    services:
    - name: immich
      port: 2283
  tls:
    secretName: immich-certificate-secret
