---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: servarr-ingressroute-certificate
  namespace: media
spec:
  secretName: servarr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - prowlarr.kube.eggenberg.io
  - radarr.kube.eggenberg.io
  - sonarr.kube.eggenberg.io
  - cleanuparr.kube.eggenberg.io
  - huntarr.kube.eggenberg.io