apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: servarr-ingressroute
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`prowlarr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: servarr-gateway
      port: 9696
  - match: Host(`radarr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: servarr-gateway
      port: 7878
  - match: Host(`sonarr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: servarr-gateway
      port: 8989
  - match: Host(`cleanuparr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: servarr-gateway
      port: 11011
  - match: Host(`huntarr.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: servarr-gateway
      port: 9705
  tls:
    secretName: servarr-certificate-secret