apiVersion: v1
kind: Service
metadata:
  name: servarr-gateway
  namespace: media
spec:
  selector:
    app: servarr
  ports:
    - name: prowlarr
      port: 9696
    - name: flaresolverr
      port: 8191
    - name: radarr
      port: 7878
    - name: sonarr
      port: 8989
    - name: cleanuparr
      port: 11011
    - name: huntarr
      port: 9705