---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gateway-proton-secret
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBa1/wzEg9XQoKppR4UsHJDem5XUcX6JmO1ZdveuV2e/+gQLgKXS4pllBZ8eCPohbPkaZhv/qvpPjL2R/xvYXlT+oXIZ83wIgGVIYvP67Z6IIfmrG5Ii61d/Bw7fb5wz4vaiJxaAumVO0Z1gQA5mNJDKSleup6oFMDXH4lNs3yvILhtEUZK1gQIqfFszaHWe6iyM2nYI0R/G7cq/V9cAv22Wtq9nhR4xuOsF8Z2Ac4ZQOlIlvTz81pn6ZFlbFdn8AtC5htizyR+EzfwSBpTTlnT/FOwoR+Yq+ZJJyebXp/5K7AB+ZYXHX11xNUlreq8cAbpTJMNZhA4yrCVtlT6BbOuaDpjWGOc9yQvm7TKmwq50030q8mnUV7kuJ1j1YgnxifU+s5KVs31gN+dacwChs+18kELh1kkVBFQdOSsZEe4HPDS/3maXshzRT0Q4fzsnaW7c5hHsPZ6oTRZmIO46yfn0kSo1OB87ME5IiWFjVDF+k2NJXl0sC2cIBd7DB6y4bPZAbaHgbO4WaznpI4VpmqIwL5nsBMrxtbuJ63a5nwS+1YdcKTT+4PLA9TOYEUet9tMUS2CmybivAufQf/Awjo1fxlwL4UY7eHJvMwJH0z7ZzxVcEcCfpSmKzenEiPYXvNy5UYOtntDEV2zuY5GC9SERT8/CYqUiDvvlf9kKymnfIq5LuPN0t9mHS6kuqib7UoVPQhwMsENt+M5vkw/5GVx1s4tGdS3i7mc+kWHjtmWulwEa9B6QdSiAWi+fQ==
  template:
    metadata:
      name: gateway-proton-secret
      namespace: media
    type: Opaque