k3s:
    token: ENC[AES256_GCM,data:J7zrHl1l0XQbLA5+wF7MZ+2GRGXVBWpF20pidRIZUF26BEjfDMeT/JIB09Ggc+BvCCqMm3opA2JXqJXufDOe+co5LNZrN4Cf3DHNY2wN9Ya/7cXpjy7bY3dKuO3rkcsHJbEBP4euu1dZrqyY,iv:XpDg6rcN5XOVCH5dpJ8HxOu/MjP357lz60XQLNBqo3c=,tag:5f/HSeTt7+ltQZXHkKu1Jg==,type:str]
sops:
    age:
        - recipient: age1hlkhznl99sc8kh33weq7z90xdrsqz85wu5c86x7kf5pkxqvum3pq2n4d7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TGlCdXl0TzBqVi9OaXQ1
            UnZqNnhjZmMvZlJjSENDYkxDVU5sVm0vK0FJCk9UR04yQno3QUFCbmtVdERiRzF6
            MHRPY0Q2RDBOdHptdGxqc29DMXlVYTgKLS0tIFYvbnVuWkd6ODUzckZEUVc3Qnhk
            TjY2S1lTWCtvQzEzY3J5Vm9kV3prZlEKJcwMyNNJELVS3NrC9ft0Htm66RZ2LBFP
            trJSZmL22sAJZRN2Ucfs9QQBU6ZcwaMYvL6BOAViJD52HxkJt25y8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ch0wn0mrwnnckp54a0742hl39053ajgwrhn0459tejt0l0uryduq9kxsqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncHVzQjlLOHpmYytvL01P
            TGFvOTloYkNOMW56SHE4RnkzYUhnMHQ1T0hrClVVTVhXSmVqbEs3bE1mb0ZTTm5v
            T3JOalFqVFR5OW9JOUI1TzNYRWhvcDAKLS0tIHU1dDJ6SFg0T01pRU5RbmpndHVU
            VlNqVVBwV09PQ3dSc0lYNlVXcElTTTgKCW+tOt5THP9Sp+1Twmq7INzTBVaed8Xd
            skHELNWKQcmsXvWTXeqXBxeXe1+J+2iFClPc2MAWi/dz0FjKsXX0HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T16:05:34Z"
    mac: ENC[AES256_GCM,data:JU3swdgd93NQzlHXC7SCNXykl3P95jNECL6WQERq12ygAKxUPdiC7c3OtP9IENLtjG8EGuYt0SZvS5Chwx8Ou9Jp/bBXcAQIOmtCrUfpZqnqD9exrUy1hvq/h9R0TEJBwvkO+vEzwRz3+SZZV1JAT86kKN2U02UF1SioP3Weigk=,iv:tCsHa27dfysU2EPHj85vDEvFc5B8xh/dlk81cvkF+Rc=,tag:egg5rv/cpm+I38mAxgXLvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
